//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int Id { get; set; }
        public int degreeMorning { get; set; }
        public int degreeAfternoon { get; set; }
        public int precipitation { get; set; }
        public int humidity { get; set; }
        public int wind { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual City City { get; set; }
    }
}
